// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RahalWeb.Models;

#nullable disable

namespace RahalWeb.Migrations
{
    [DbContext(typeof(RahalWebContext))]
    [Migration("20260601000000_AddContractSuspendToPasswordDatum")]
    partial class AddContractSuspendToPasswordDatum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RahalWeb.Models.PasswordDatum", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("ContractSuspend")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("PasswordData");
            });
#pragma warning restore 612, 618
        }
    }
}
