// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RahalWeb.Models;

#nullable disable

namespace RahalWeb.Migrations
{
    [DbContext(typeof(RahalWebContext))]
    [Migration("20260216060115_DeffTreament2")]
    partial class DeffTreament2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RahalWeb.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankBillNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("BankDate")
                        .HasColumnType("date");

                    b.Property<int?>("BankIntNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("BillDate")
                        .HasColumnType("date");

                    b.Property<string>("BillHent")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("no");

                    b.Property<int?>("BillNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("BillPayed")
                        .HasColumnType("money");

                    b.Property<TimeOnly?>("BillTime")
                        .HasColumnType("time");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("DeleteReson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<int?>("LateDays")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<DateOnly?>("UserRecievedDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserRecievedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserRecievedNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankIntNo");

                    b.HasIndex("ContractId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("Bill", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.CarInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarCode")
                        .HasColumnType("int");

                    b.Property<string>("CarColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CarCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("CarEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CarEndLicense")
                        .HasColumnType("date");

                    b.Property<int?>("CarKindId")
                        .HasColumnType("int");

                    b.Property<int?>("CarModel")
                        .HasColumnType("int");

                    b.Property<string>("CarNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CarNoOfSystemRound")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CarPaper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CarReg")
                        .HasColumnType("date");

                    b.Property<int?>("CarShapeId")
                        .HasColumnType("int");

                    b.Property<string>("CarShase")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CarTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NoOfCredit")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RegDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarKindId");

                    b.HasIndex("CarShapeId");

                    b.HasIndex("CarTypeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("CarInfo", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.CarInfoAtt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("PathFileData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarInfoAtt", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyDebit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompDebitNo")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DebitDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DebitQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DebitReson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeletFlag")
                        .HasColumnType("int");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("OtherData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PayedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReminderQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserRecievedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompDebitNo");

                    b.HasIndex("DebitDate");

                    b.HasIndex("EmpId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserRecievedId");

                    b.ToTable("CompanyDebit", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyDebitDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CompDebitDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("CompDebitDetailsNo")
                        .HasColumnType("int");

                    b.Property<int?>("CompDebitId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CompDebitPayed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CompDebitType")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("UserRecievedDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("UserRecievedId")
                        .HasColumnType("int");

                    b.Property<int?>("UserRecievedNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompDebitDate");

                    b.HasIndex("CompDebitId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserRecievedId");

                    b.ToTable("CompanyDebitDetails", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AcceptNewerDate")
                        .HasColumnType("date");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CompActivateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CompAutoNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CompCode")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CompEndDate")
                        .HasColumnType("date");

                    b.Property<string>("CompFileNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompLicenseNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompLogo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompNameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompOwnerNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompPaper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CompReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerCivilId1")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("OwnerCivilID1");

                    b.Property<string>("OwnerCivilId2")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("OwnerCivilID2");

                    b.Property<string>("OwnerCivilId3")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("OwnerCivilID3");

                    b.Property<string>("OwnerName1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OwnerName2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OwnerName3")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("RegDate")
                        .HasColumnType("date");

                    b.Property<string>("Tel1")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Tel2")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompActivateId");

                    b.HasIndex("LocationId");

                    b.ToTable("CompanyInfo", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyInfoAtt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<string>("PathFileData")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TitleData")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CompId");

                    b.ToTable("CompanyInfoAtt", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ContractDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractEndReson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ContractType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("CreditEndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("CreditMonthPay")
                        .HasColumnType("money");

                    b.Property<int?>("CreditNoOfMonth")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CreditStartDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("CreditTotalCost")
                        .HasColumnType("money");

                    b.Property<decimal?>("DailyCredit")
                        .HasColumnType("money");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("HaveVacation")
                        .HasColumnType("bit");

                    b.Property<int?>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("money");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.ContractDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CarCredit")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DailyCredit")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<DateOnly?>("DailyCreditDate")
                        .HasColumnType("date");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("PayedDate")
                        .HasColumnType("date");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractDetails");
                });

            modelBuilder.Entity("RahalWeb.Models.CreditBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankBillNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("BankDate")
                        .HasColumnType("date");

                    b.Property<int?>("BankIntNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("BillHent")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("no");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CreditBillDate")
                        .HasColumnType("date");

                    b.Property<int?>("CreditBillNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("CreditBillPayed")
                        .HasColumnType("money");

                    b.Property<TimeOnly?>("CreditBillTime")
                        .HasColumnType("time");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("DeleteReson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<int?>("LateMonth")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfMonth")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<DateOnly?>("UserRecievedDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserRecievedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("BankIntNo");

                    b.HasIndex("ContractId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditBill", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.DebitInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DebitDate")
                        .HasColumnType("date");

                    b.Property<string>("DebitDescrp")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DebitNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("DebitPayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("DebitQty")
                        .HasColumnType("money");

                    b.Property<decimal?>("DebitRemaining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<int?>("DebitTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("DeleteReson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DebitTypeId");

                    b.HasIndex("EmpId");

                    b.HasIndex("UserId");

                    b.HasIndex("ViolationId");

                    b.ToTable("DebitInfo", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.DebitPayInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DebitInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("DebitPayDate")
                        .HasColumnType("date");

                    b.Property<int?>("DebitPayNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("DebitPayQty")
                        .HasColumnType("money");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("DeleteReson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Hent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("UserRecievedDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserRecievedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserRecievedNo")
                        .HasColumnType("int");

                    b.Property<int?>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DebitInfoId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserRecievedId");

                    b.HasIndex("ViolationId");

                    b.ToTable("DebitPayInfo", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.Deff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeffCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DeffName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeffNameEng")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DeffParent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("DeffType")
                        .HasColumnType("int");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DeffType");

                    b.ToTable("Deff", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.DeffEmpTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeffCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeffName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("Price1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price3")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DeffEmpTreatment", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.DeffInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DebitPayLatId")
                        .HasColumnType("int");

                    b.Property<double?>("DebitPayLateDay")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DebitPayLatId")
                        .IsUnique()
                        .HasFilter("[DebitPayLatId] IS NOT NULL");

                    b.ToTable("DeffInformation");
                });

            modelBuilder.Entity("RahalWeb.Models.DeffType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeffType", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.EmployeeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoAddressNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CivilId")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("CivilID");

                    b.Property<DateOnly?>("CivilIdendDate")
                        .HasColumnType("date")
                        .HasColumnName("CivilIDEndDate");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("EmpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EmpBirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("EmpCode")
                        .HasColumnType("int");

                    b.Property<bool>("EmpDepMang")
                        .HasColumnType("bit");

                    b.Property<string>("EmpPic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndLicense")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndPerm")
                        .HasColumnType("date");

                    b.Property<string>("FirstNameAr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ForthNameAr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ForthNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullNameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullNameEN");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("LastNameAr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("MobiileNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PassportEndDate")
                        .HasColumnType("date");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("PassportStartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RegDate")
                        .HasColumnType("date");

                    b.Property<int?>("RelationId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ResEndDate")
                        .HasColumnType("date");

                    b.Property<string>("ResNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("money");

                    b.Property<string>("SecondNameAr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("StartLicense")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartPerm")
                        .HasColumnType("date");

                    b.Property<string>("TelNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThirdNameAr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThirdNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("LocationId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("RelationId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeInfo", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.EmployeeInfoAtt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PathFileData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.ToTable("EmployeeInfoAtt", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.EmployeeSalary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddBasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AddFood")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AddRoom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AddSpecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AddTravel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Approve")
                        .HasColumnType("int");

                    b.Property<decimal>("DeductAdvance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeductPenality")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeductRoom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("EmpSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpSalaryMonth")
                        .HasColumnType("int");

                    b.Property<int>("EmpSalaryYear")
                        .HasColumnType("int");

                    b.Property<decimal>("EmpSpecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Net")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalaryRecieved")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDeduuct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPayed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeSalary", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.EmployeeTakeMoney", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeleteFlag")
                        .HasColumnType("int");

                    b.Property<string>("EmpReson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("TakeDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TakeMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TakeMoneyNo")
                        .HasColumnType("int");

                    b.Property<int>("TakeUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TakeUserId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeTakeMoney");
                });

            modelBuilder.Entity("RahalWeb.Models.PasswordDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CarArchive")
                        .HasColumnType("bit");

                    b.Property<bool>("CarSave")
                        .HasColumnType("bit");

                    b.Property<bool>("CarView")
                        .HasColumnType("bit");

                    b.Property<bool>("Cardelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CompDebitDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CompDebitSave")
                        .HasColumnType("bit");

                    b.Property<bool>("CompDebitUpdate")
                        .HasColumnType("bit");

                    b.Property<bool>("CompDebitView")
                        .HasColumnType("bit");

                    b.Property<bool>("CompDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CompSave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CompView")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("CompanyData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ContractArchive")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractChangeCar")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractChangeRent")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractDailyEnd")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractDailySave")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractDailyView")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractMonthlyEnd")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractMonthlySave")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractMonthlyView")
                        .HasColumnType("bit");

                    b.Property<bool>("DebitDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("DebitLatePay")
                        .HasColumnType("bit");

                    b.Property<bool>("DebitPay")
                        .HasColumnType("bit");

                    b.Property<bool>("DebitSave")
                        .HasColumnType("bit");

                    b.Property<bool>("DebitUpdate")
                        .HasColumnType("bit");

                    b.Property<bool>("DebitView")
                        .HasColumnType("bit");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("EmpArchive")
                        .HasColumnType("bit");

                    b.Property<bool>("EmpDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("EmpSave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EmpTakeMoney")
                        .HasColumnType("bit");

                    b.Property<bool>("EmpView")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PayDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("PaySave")
                        .HasColumnType("bit");

                    b.Property<bool>("PayView")
                        .HasColumnType("bit");

                    b.Property<bool>("PurshaseDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("PurshaseSave")
                        .HasColumnType("bit");

                    b.Property<bool>("PurshaseShowAll")
                        .HasColumnType("bit");

                    b.Property<bool>("PurshaseUpdate")
                        .HasColumnType("bit");

                    b.Property<bool>("PurshaseView")
                        .HasColumnType("bit");

                    b.Property<bool>("RecievedMoney")
                        .HasColumnType("bit");

                    b.Property<string>("RecievedPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("UserAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("VacationView")
                        .HasColumnType("bit");

                    b.Property<bool>("ViolationDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("ViolationSave")
                        .HasColumnType("bit");

                    b.Property<bool>("ViolationUpdate")
                        .HasColumnType("bit");

                    b.Property<bool>("ViolationView")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PasswordData");
                });

            modelBuilder.Entity("RahalWeb.Models.Purshase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("CompId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PurshaseBillNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("PurshaseDate")
                        .HasColumnType("date");

                    b.Property<string>("PurshaseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PurshaseId")
                        .HasColumnType("int");

                    b.Property<int?>("PurshaseNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("PurshasePayed")
                        .HasColumnType("money");

                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("PurshaseId");

                    b.ToTable("Purshase", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.UserCompanyNotAppear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCompanyNotAppear", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<int?>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<int?>("VacationPayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("VacationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.ToTable("Vacation", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.ViolationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<int?>("TransfereToDebit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("ViolationBookNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("ViolationCost")
                        .HasColumnType("money");

                    b.Property<DateOnly?>("ViolationDate")
                        .HasColumnType("date");

                    b.Property<int?>("ViolationGuideId")
                        .HasColumnType("int");

                    b.Property<string>("ViolationNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ViolationPlace")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ViolationPoint")
                        .HasColumnType("int");

                    b.Property<double?>("ViolationSpeed")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ViolationTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("EmpId");

                    b.HasIndex("UserId");

                    b.HasIndex("ViolationGuideId");

                    b.ToTable("ViolationInfo", (string)null);
                });

            modelBuilder.Entity("RahalWeb.Models.Bill", b =>
                {
                    b.HasOne("RahalWeb.Models.Deff", "BankIntNoNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("BankIntNo")
                        .HasConstraintName("FK_Bill_Deff");

                    b.HasOne("RahalWeb.Models.Contract", "Contract")
                        .WithMany("Bills")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_Bill_Contract");

                    b.HasOne("RahalWeb.Models.EmployeeInfo", "Employee")
                        .WithMany("Bills")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Bill_EmployeeInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("Bills")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Bill_PasswordData");

                    b.Navigation("BankIntNoNavigation");

                    b.Navigation("Contract");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RahalWeb.Models.CarInfo", b =>
                {
                    b.HasOne("RahalWeb.Models.Deff", "CarKind")
                        .WithMany("CarInfoCarKinds")
                        .HasForeignKey("CarKindId")
                        .HasConstraintName("FK_CarInfo_Deff3");

                    b.HasOne("RahalWeb.Models.Deff", "CarShape")
                        .WithMany("CarInfoCarShapes")
                        .HasForeignKey("CarShapeId")
                        .HasConstraintName("FK_CarInfo_Deff1");

                    b.HasOne("RahalWeb.Models.Deff", "CarType")
                        .WithMany("CarInfoCarTypes")
                        .HasForeignKey("CarTypeId")
                        .HasConstraintName("FK_CarInfo_Deff");

                    b.HasOne("RahalWeb.Models.CompanyInfo", "Company")
                        .WithMany("CarInfos")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_CarInfo_CompanyInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("CarInfos")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_CarInfo_PasswordData");

                    b.Navigation("CarKind");

                    b.Navigation("CarShape");

                    b.Navigation("CarType");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RahalWeb.Models.CarInfoAtt", b =>
                {
                    b.HasOne("RahalWeb.Models.CarInfo", "Car")
                        .WithMany("CarInfoAtts")
                        .HasForeignKey("CarId")
                        .HasConstraintName("FK_CarInfoAtt_CarInfo");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyDebit", b =>
                {
                    b.HasOne("RahalWeb.Models.EmployeeInfo", "Employee")
                        .WithMany("CompanyDebits")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CompanyDebit_Employee");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "UserInfo")
                        .WithMany("CompanyDebitsUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CompanyDebit_UserInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "UserInfoRecieve")
                        .WithMany("CompanyDebitsUserRecieved")
                        .HasForeignKey("UserRecievedId")
                        .HasConstraintName("FK_CompanyDebit_UserInfoRecieve");

                    b.Navigation("Employee");

                    b.Navigation("UserInfo");

                    b.Navigation("UserInfoRecieve");
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyDebitDetails", b =>
                {
                    b.HasOne("RahalWeb.Models.CompanyDebit", "CompanyDebits")
                        .WithMany("CompanyDebitsDetails")
                        .HasForeignKey("CompDebitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CompanyDebitDetails_CompanyDebit");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "UserInfo")
                        .WithMany("CompanyDebitsDetailsUser")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_CompanyDebitDetails_UserInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "UserInfoRecieve")
                        .WithMany("CompanyDebitsDetailsUserRecieved")
                        .HasForeignKey("UserRecievedId")
                        .HasConstraintName("FK_CompanyDebitDetails_UserInfoRecieve");

                    b.Navigation("CompanyDebits");

                    b.Navigation("UserInfo");

                    b.Navigation("UserInfoRecieve");
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyInfo", b =>
                {
                    b.HasOne("RahalWeb.Models.Deff", "City")
                        .WithMany("CompanyInfoCities")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_CompanyInfo_Deff1");

                    b.HasOne("RahalWeb.Models.Deff", "CompActivate")
                        .WithMany("CompanyInfoCompActivates")
                        .HasForeignKey("CompActivateId")
                        .HasConstraintName("FK_CompanyInfo_Deff2");

                    b.HasOne("RahalWeb.Models.Deff", "Location")
                        .WithMany("CompanyInfoLocations")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK_CompanyInfo_Deff");

                    b.Navigation("City");

                    b.Navigation("CompActivate");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyInfoAtt", b =>
                {
                    b.HasOne("RahalWeb.Models.CompanyInfo", "Comp")
                        .WithMany("CompanyInfoAtts")
                        .HasForeignKey("CompId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CompanyInfoAtt_CompanyInfo");

                    b.Navigation("Comp");
                });

            modelBuilder.Entity("RahalWeb.Models.Contract", b =>
                {
                    b.HasOne("RahalWeb.Models.CarInfo", "Car")
                        .WithMany("Contracts")
                        .HasForeignKey("CarId")
                        .HasConstraintName("FK_Contract_CarInfo");

                    b.HasOne("RahalWeb.Models.EmployeeInfo", "Employee")
                        .WithMany("Contracts")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Contract_EmployeeInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("Contracts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Contract_PasswordData");

                    b.Navigation("Car");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RahalWeb.Models.ContractDetail", b =>
                {
                    b.HasOne("RahalWeb.Models.Bill", "Bill")
                        .WithMany("ContractDetails")
                        .HasForeignKey("BillId")
                        .HasConstraintName("FK_ContractDetails_Bill");

                    b.HasOne("RahalWeb.Models.Contract", "Contract")
                        .WithMany("ContractDetails")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_ContractDetails_Contract");

                    b.Navigation("Bill");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("RahalWeb.Models.CreditBill", b =>
                {
                    b.HasOne("RahalWeb.Models.Deff", "BankIntNoNavigation")
                        .WithMany("CreditBills")
                        .HasForeignKey("BankIntNo")
                        .HasConstraintName("FK_CreditBill_Deff");

                    b.HasOne("RahalWeb.Models.Contract", "Contract")
                        .WithMany("CreditBills")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_CreditBill_Contract");

                    b.HasOne("RahalWeb.Models.EmployeeInfo", "Employee")
                        .WithMany("CreditBills")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_CreditBill_EmployeeInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("CreditBills")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_CreditBill_PasswordData");

                    b.Navigation("BankIntNoNavigation");

                    b.Navigation("Contract");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RahalWeb.Models.DebitInfo", b =>
                {
                    b.HasOne("RahalWeb.Models.Deff", "DebitType")
                        .WithMany("DebitInfoDebitTypes")
                        .HasForeignKey("DebitTypeId")
                        .HasConstraintName("FK_DebitInfo_Deff2");

                    b.HasOne("RahalWeb.Models.EmployeeInfo", "Emp")
                        .WithMany("DebitInfos")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("FK_DebitInfo_EmployeeInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("DebitInfos")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DebitInfo_PasswordData");

                    b.HasOne("RahalWeb.Models.Deff", "Violation")
                        .WithMany("DebitInfoViolations")
                        .HasForeignKey("ViolationId")
                        .HasConstraintName("FK_DebitInfo_Deff3");

                    b.Navigation("DebitType");

                    b.Navigation("Emp");

                    b.Navigation("User");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("RahalWeb.Models.DebitPayInfo", b =>
                {
                    b.HasOne("RahalWeb.Models.DebitInfo", "DebitInfo")
                        .WithMany("DebitPayInfos")
                        .HasForeignKey("DebitInfoId")
                        .HasConstraintName("FK_DebitPayInfo_DebitInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("DebitPayInfoUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DebitPayInfo_PasswordData");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "UserRecieved")
                        .WithMany("DebitPayInfoUserRecieveds")
                        .HasForeignKey("UserRecievedId")
                        .HasConstraintName("FK_DebitPayInfo_PasswordData1");

                    b.HasOne("RahalWeb.Models.ViolationInfo", "ViolationInfo")
                        .WithMany("DebitPayInfos")
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DebitPayInfo_ViolationInfo");

                    b.Navigation("DebitInfo");

                    b.Navigation("User");

                    b.Navigation("UserRecieved");

                    b.Navigation("ViolationInfo");
                });

            modelBuilder.Entity("RahalWeb.Models.Deff", b =>
                {
                    b.HasOne("RahalWeb.Models.DeffType", "DeffTypeNavigation")
                        .WithMany("Deffs")
                        .HasForeignKey("DeffType")
                        .HasConstraintName("FK_Deff_DeffType");

                    b.Navigation("DeffTypeNavigation");
                });

            modelBuilder.Entity("RahalWeb.Models.DeffInformation", b =>
                {
                    b.HasOne("RahalWeb.Models.Deff", "DeffPayLate")
                        .WithOne("DeffInformation")
                        .HasForeignKey("RahalWeb.Models.DeffInformation", "DebitPayLatId");

                    b.Navigation("DeffPayLate");
                });

            modelBuilder.Entity("RahalWeb.Models.EmployeeInfo", b =>
                {
                    b.HasOne("RahalWeb.Models.CompanyInfo", "Company")
                        .WithMany("EmployeeInfos")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_EmployeeInfo_CompanyInfo");

                    b.HasOne("RahalWeb.Models.Deff", "JobTitle")
                        .WithMany("EmployeeInfoJobTitles")
                        .HasForeignKey("JobTitleId")
                        .HasConstraintName("FK_EmployeeInfo_Deff");

                    b.HasOne("RahalWeb.Models.Deff", "Location")
                        .WithMany("EmployeeInfoLocations")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK_EmployeeInfo_Deff3");

                    b.HasOne("RahalWeb.Models.Deff", "Nationality")
                        .WithMany("EmployeeInfoNationalities")
                        .HasForeignKey("NationalityId")
                        .HasConstraintName("FK_EmployeeInfo_Deff1");

                    b.HasOne("RahalWeb.Models.Deff", "Relation")
                        .WithMany("EmployeeInfoRelations")
                        .HasForeignKey("RelationId")
                        .HasConstraintName("FK_EmployeeInfo_Deff2");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("EmployeeInfos")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_EmployeeInfo_PasswordData");

                    b.Navigation("Company");

                    b.Navigation("JobTitle");

                    b.Navigation("Location");

                    b.Navigation("Nationality");

                    b.Navigation("Relation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RahalWeb.Models.EmployeeInfoAtt", b =>
                {
                    b.HasOne("RahalWeb.Models.EmployeeInfo", "Emp")
                        .WithMany("EmployeeInfoAtts")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("FK_EmployeeInfoAtt_EmployeeInfo");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("RahalWeb.Models.EmployeeSalary", b =>
                {
                    b.HasOne("RahalWeb.Models.EmployeeInfo", "Emp")
                        .WithMany("EmployeeSalarys")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeSalary_EmployeeInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("EmployeeSalarys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeSalary_PasswordData");

                    b.Navigation("Emp");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RahalWeb.Models.EmployeeTakeMoney", b =>
                {
                    b.HasOne("RahalWeb.Models.PasswordDatum", "TakeUser")
                        .WithMany("EmployeeTakeMoneyTakeUser")
                        .HasForeignKey("TakeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeTakeMoneyTakeUser_PasswordData");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("EmployeeTakeMoneyUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeTakeMoneyUser_PasswordData");

                    b.Navigation("TakeUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RahalWeb.Models.Purshase", b =>
                {
                    b.HasOne("RahalWeb.Models.Deff", "PurshaseNavigation")
                        .WithMany("Purshases")
                        .HasForeignKey("PurshaseId")
                        .HasConstraintName("FK_Purshase_Deff");

                    b.Navigation("PurshaseNavigation");
                });

            modelBuilder.Entity("RahalWeb.Models.UserCompanyNotAppear", b =>
                {
                    b.HasOne("RahalWeb.Models.CompanyInfo", "Company")
                        .WithMany("UserCompanyNotAppears")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_UserCompanyNotAppear_CompanyInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("UserCompanyNotAppears")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserCompanyNotAppear_PasswordData");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RahalWeb.Models.Vacation", b =>
                {
                    b.HasOne("RahalWeb.Models.EmployeeInfo", "Emp")
                        .WithMany("Vacations")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("FK_Vacation_EmployeeInfo");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("RahalWeb.Models.ViolationInfo", b =>
                {
                    b.HasOne("RahalWeb.Models.CarInfo", "Car")
                        .WithMany("ViolationInfos")
                        .HasForeignKey("CarId")
                        .HasConstraintName("FK_ViolationInfo_CarInfo");

                    b.HasOne("RahalWeb.Models.EmployeeInfo", "Employee")
                        .WithMany("ViolationInfos")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("FK_ViolationInfo_EmployeeInfo");

                    b.HasOne("RahalWeb.Models.PasswordDatum", "User")
                        .WithMany("ViolationInfos")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ViolationInfo_PasswordData");

                    b.HasOne("RahalWeb.Models.Deff", "ViolationGuide")
                        .WithMany("ViolationInfos")
                        .HasForeignKey("ViolationGuideId")
                        .HasConstraintName("FK_ViolationInfo_Deff");

                    b.Navigation("Car");

                    b.Navigation("Employee");

                    b.Navigation("User");

                    b.Navigation("ViolationGuide");
                });

            modelBuilder.Entity("RahalWeb.Models.Bill", b =>
                {
                    b.Navigation("ContractDetails");
                });

            modelBuilder.Entity("RahalWeb.Models.CarInfo", b =>
                {
                    b.Navigation("CarInfoAtts");

                    b.Navigation("Contracts");

                    b.Navigation("ViolationInfos");
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyDebit", b =>
                {
                    b.Navigation("CompanyDebitsDetails");
                });

            modelBuilder.Entity("RahalWeb.Models.CompanyInfo", b =>
                {
                    b.Navigation("CarInfos");

                    b.Navigation("CompanyInfoAtts");

                    b.Navigation("EmployeeInfos");

                    b.Navigation("UserCompanyNotAppears");
                });

            modelBuilder.Entity("RahalWeb.Models.Contract", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("ContractDetails");

                    b.Navigation("CreditBills");
                });

            modelBuilder.Entity("RahalWeb.Models.DebitInfo", b =>
                {
                    b.Navigation("DebitPayInfos");
                });

            modelBuilder.Entity("RahalWeb.Models.Deff", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("CarInfoCarKinds");

                    b.Navigation("CarInfoCarShapes");

                    b.Navigation("CarInfoCarTypes");

                    b.Navigation("CompanyInfoCities");

                    b.Navigation("CompanyInfoCompActivates");

                    b.Navigation("CompanyInfoLocations");

                    b.Navigation("CreditBills");

                    b.Navigation("DebitInfoDebitTypes");

                    b.Navigation("DebitInfoViolations");

                    b.Navigation("DeffInformation");

                    b.Navigation("EmployeeInfoJobTitles");

                    b.Navigation("EmployeeInfoLocations");

                    b.Navigation("EmployeeInfoNationalities");

                    b.Navigation("EmployeeInfoRelations");

                    b.Navigation("Purshases");

                    b.Navigation("ViolationInfos");
                });

            modelBuilder.Entity("RahalWeb.Models.DeffType", b =>
                {
                    b.Navigation("Deffs");
                });

            modelBuilder.Entity("RahalWeb.Models.EmployeeInfo", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("CompanyDebits");

                    b.Navigation("Contracts");

                    b.Navigation("CreditBills");

                    b.Navigation("DebitInfos");

                    b.Navigation("EmployeeInfoAtts");

                    b.Navigation("EmployeeSalarys");

                    b.Navigation("Vacations");

                    b.Navigation("ViolationInfos");
                });

            modelBuilder.Entity("RahalWeb.Models.PasswordDatum", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("CarInfos");

                    b.Navigation("CompanyDebitsDetailsUser");

                    b.Navigation("CompanyDebitsDetailsUserRecieved");

                    b.Navigation("CompanyDebitsUser");

                    b.Navigation("CompanyDebitsUserRecieved");

                    b.Navigation("Contracts");

                    b.Navigation("CreditBills");

                    b.Navigation("DebitInfos");

                    b.Navigation("DebitPayInfoUserRecieveds");

                    b.Navigation("DebitPayInfoUsers");

                    b.Navigation("EmployeeInfos");

                    b.Navigation("EmployeeSalarys");

                    b.Navigation("EmployeeTakeMoneyTakeUser");

                    b.Navigation("EmployeeTakeMoneyUser");

                    b.Navigation("UserCompanyNotAppears");

                    b.Navigation("ViolationInfos");
                });

            modelBuilder.Entity("RahalWeb.Models.ViolationInfo", b =>
                {
                    b.Navigation("DebitPayInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
