// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RahalWeb.Models;

#nullable disable

namespace RahalWeb.Migrations
{
    [DbContext(typeof(RahalWebContext))]
    [Migration("20260531000000_AddStopReasonToContractDetail")]
    partial class AddStopReasonToContractDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RahalWeb.Models.ContractDetail", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int?>("BillId")
                    .HasColumnType("int");

                b.Property<decimal?>("CarCredit")
                    .HasColumnType("decimal(18, 3)");

                b.Property<int?>("ContractId")
                    .HasColumnType("int");

                b.Property<decimal?>("DailyCredit")
                    .HasColumnType("decimal(18, 3)");

                b.Property<DateOnly?>("DailyCreditDate")
                    .HasColumnType("date");

                b.Property<int?>("DeleteFlag")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<DateOnly?>("PayedDate")
                    .HasColumnType("date");

                b.Property<int?>("Status")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<string>("StopReason")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.HasKey("Id");

                b.HasIndex("BillId");

                b.HasIndex("ContractId");

                b.ToTable("ContractDetails");
            });
#pragma warning restore 612, 618
        }
    }
}